### ISSUE TITLE
Create multiple resources

### ISSUE THREAD

**Issue by erfanasbari** [mtasa-typescript/resource-boilerplate#27]
Is there a way to create and develop multiple resources is different folders and build them at the same time? (I don't want to clone this boilerplate for every single resource)

For example MTA SA default server has multiple folders and inside them are multiple resources.

Is there a simple way to do this or I have to write some special script for it?

Thanks.

**Comment by Toliak** [comment]
Hello, @erfanasbari !
There is a dirty trick to make multiple resources from the same boilerplate.

Step 1. Put the boilerplate into directory named `[something_like_that]`. Name **should** be in square brackets (because MTASA interprets that like a "directory with resources".

Step 2. Change 
```ts
"outDir": "lua",
```
to
```ts
"outDir": "[lua]",
```
in `tsconfig.json` file

Step 3. Put some code and build it
![image](https://user-images.githubusercontent.com/25643405/126363530-0f9b5e8c-95f7-4f38-a55f-54c4d503e3ee.png)

Step 4. Copy `meta.xml` and `lualib_bundle.lua` into each resource directory (in my case, into `[lua]/resource_1`, `[lua]/resource_2`, `[lua]/resource_3`)

Step 5. Modify `meta.xml`. (Example for my case below)
```xml
<meta>
    <info author="" type="script" name="TS Resource" />

    <!-- Bundle files -->
    <script src="lualib_bundle.lua" cache="false" type="shared"/>

    <!-- Compiled files -->
    <script src="server.lua" type="server"/>

    <!-- Enables MTASA Classes -->
    <oop>true</oop>
</meta>
```

Now resources are ready to be loaded
![image](https://user-images.githubusercontent.com/25643405/126363896-96488ff9-41d2-4061-a45a-f7e950d42886.png)


Anyway, I will not close this issue, because the idea is very interesting and I haven't thought about that before. So, in the future I will provide a better way to achieve multiple-resource building :)

**Comment by erfanasbari** [comment]
Thanks @Toliak for quick respond and great solution!

After posting this issue I thought to myself for a second and remembered every thing that I put inside `src` folder will be included in `outDir` (Thats how typescript works, sorry I didn't think enough before posting the issue).

> Copy meta.xml and lualib_bundle.lua into each resource directory (in my case, into [lua]/resource_1, [lua]/resource_2, [lua]/resource_3)

Typescript only includes the files that are getting compiled in the build folder so the `meta.xml` for each resource should be moved manually into each built resource.

To fix that I think you can create a `ttypescript` transformer or use `copyfiles` package.
I'll take a look at how to create a `ttypescript` transformer and create one if it's possible.

**Comment by erfanasbari** [comment]
I didn't look at the `ttypescript` transformer but I think `copyfiles` is the easier and better solution.
I'll try fixing it and create a pull request if you agree.

**Comment by Toliak** [comment]
Yes, good idea!
`ttypescript` transformer is not necessary here, because we are not working with TypeScript AST to copy files =)

Also, you can modify [mtasa-lua-utils](https://github.com/mtasa-typescript/mtasa-lua-utils) package and then create pull request into it.
Btw, I'm using [this](https://github.com/mtasa-typescript/mtasa-lua-utils/blob/master/utils/postbuild.js) script to validate meta.xml, so you can call `copyfiles` from it
